name: R-CI

on:
  push:
    branches: [ develop, cicd ]
  pull_request:
    branches: [ develop, cicd ]
    types: [opened, closed, reopened]
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ./r-libs

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Make R lib folder if it doesn't exist
        run: mkdir -p ${{ env.R_LIBS_USER }}

      - name: Cache R packages
        uses: actions/cache@v2
        id: cache-r
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/survey/DESCRIPTION') }}

      - name: Install R packages
        shell: Rscript {0}
        run: install.packages("survey")
        if: steps.cache-r.outputs.cache-hit != 'true'

      - name: Login Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

#      - name: Jira TODO
#        uses: atlassian/gajira-todo@master
#        with:
#           project: SCD
#           issuetype: Task
#           description: Created automatically via GitHub Actions
#        env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Create new issue
#        id: create
#        uses: atlassian/gajira-create@master
#        with:
#           project: SCD
#           issuetype: Task
#           summary: Bug automatically via GitHub Actions
#           description: Created automatically via GitHub Actions
#      - name: Transition issue
#        uses: atlassian/gajira-transition@master
#        with:
#          issue: ${{ steps.create.outputs.issue }}
#          transition: "In progress"
###################################################################################
  create:
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && github.event.action == 'opened'
    runs-on: ubuntu-latest
    name: Create ticket
    steps:
    - name: Check if community user
      id: github-team-role
      run: |
        TEAM=vault
        ROLE="$(hub api orgs/hashicorp/teams/${TEAM}/memberships/${{ github.actor }} | jq -r '.role | select(.!=null)')"
        if [[ -n ${ROLE} ]]; then
          echo "Actor ${{ github.actor }} is a ${TEAM} team member, skipping Jira ticket creation"
        else
          echo "Actor ${{ github.actor }} is not a ${TEAM} team member, continuing to Jira ticket creation"
        fi
        echo "::set-output name=role::${ROLE}"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Login Jira
      if: ${{ !steps.github-team-role.outputs.role }}
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create task on jira
      if: ${{ !steps.github-team-role.outputs.role }}
      uses: tomhjp/gh-action-jira-create@v0.1.0
      with:
        project: SCD
        issuetype: "GH Issue"
        summary: "${{ github.repository }}: ${{ github.event.issue.title || github.event.pull_request.title }} #${{ github.event.issue.number || github.event.pull_request.number }}"
        description: "${{ github.event.issue.body || github.event.pull_request.body }}\n\n_Created from GitHub Action for ${{ github.event.issue.html_url || github.event.pull_request.html_url }}, from ${{ github.actor }}_"
        extraFields: '{"fixVersions": [{"name": "TBD"}], "customfield_10091": ["product"], "customfield_10089": "${{ github.event.issue.html_url || github.event.pull_request.html_url }}"}'

  sync-comment:
    if: github.event.action == 'created' || github.event.action == 'submitted'
    runs-on: ubuntu-latest
    name: Sync comment
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.2.1
      with:
        jql: 'project = "SCD" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"' # cf[10089] == Issue Link custom field

    - name: Sync comment
      if: steps.search.outputs.issue
      uses: atlassian/gajira-comment@v2.0.1
      with:
        issue: ${{ steps.search.outputs.issue }}
        comment: "${{ github.actor }} ${{ github.event.review.state || 'commented' }}:\n\n${{ github.event.comment.body || github.event.review.body }}\n\n${{ github.event.comment.html_url || github.event.review.html_url }}"

  close:
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && (github.event.action == 'closed' || github.event.action == 'deleted')
    runs-on: ubuntu-latest
    name: Close ticket
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.2.1
      with:
        jql: 'project = "SCD" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"'

    - name: Close ticket
      if: steps.search.outputs.issue
      uses: atlassian/gajira-transition@v2.0.1
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: Done

  reopen:
    if: github.event.action == 'reopened'
    runs-on: ubuntu-latest
    name: Reopen ticket
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.2.1
      with:
        # cf[10089] == Issue Link custom field
        jql: 'project = "SCD" and issuetype = "GH Issue" and cf[10089]="${{ github.event.issue.html_url || github.event.pull_request.html_url }}"'

    - name: Reopen ticket
      if: steps.search.outputs.issue
      uses: atlassian/gajira-transition@v2.0.1
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: "To Do"
